# Use config map for not-secret configuration data

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paymentservice.fullname" . }}-configmap
  labels:
    {{- include "paymentservice.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}