apiVersion: v1
kind: Service
metadata:
  name: {{ include "paymentservice.fullname" . }}-clusterip
  labels:
    {{- include "paymentservice.labels" . | nindent 4 }}

spec:
  selector:
    {{- include "paymentservice.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 32229